import Head from 'next/head';
import { useState } from 'react';

export default function Cardapio() {
  const [carrinho, setCarrinho] = useState([]);
  const [quantidades, setQuantidades] = useState({
    'X-salada': 0,
    'X-bacon': 0,
    'X-egg': 0,
    'X-frango': 0,
    'X-calabresa': 0,
    'X-tudo': 0,
    'X-vegetariano': 0,
    'Chocolate': 0,
    'Picolé': 0,
    'Palha Italiana': 0,
    'Açaí': 0,
    'Pudim': 0,
    'Suco de Laranja': 0,
    'Suco de Goiaba': 0,
    'Suco de Maçã': 0,
    'Suco de Abacaxi': 0,
  });

  const adicionarAoCarrinho = (item) => {
    const novoCarrinho = [...carrinho, { ...item, quantidade: quantidades[item.nome] }];
    setCarrinho(novoCarrinho);
    setQuantidades({ ...quantidades, [item.nome]: 0 });
  };

  const incrementarQuantidade = (nome) => {
    setQuantidades({ ...quantidades, [nome]: quantidades[nome] + 1 });
  };

  const decrementarQuantidade = (nome) => {
    if (quantidades[nome] > 0) {
      setQuantidades({ ...quantidades, [nome]: quantidades[nome] - 1 });
    }
  };

  const limparCarrinho = () => {
    setCarrinho([]);
  };

  const registrarPedido = () => {
    // Aqui você pode adicionar lógica para enviar o pedido para o servidor ou outra ação desejada
    alert('Pedido registrado com sucesso!');
  };

  return (
    <>
      <Head>
        <title>Cardápio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="menu">
        <div id="menu-container">
          {menuItens.map((categoria) => (
            <div key={categoria.titulo} className="menu-item">
              <h3 className="categoria">{categoria.titulo}</h3>
              <ul>
                {categoria.itens.map((item) => (
                  <li key={item.nome}>
                    <span className="item-nome">{item.nome}</span> - 
                    <span className="item-preco"> R${item.preco.toFixed(2)}</span>
                    <button onClick={() => decrementarQuantidade(item.nome)} className="contador">-</button>
                    <span className="quantidade contador">{quantidades[item.nome]}</span>
                    <button onClick={() => incrementarQuantidade(item.nome)} className="contador">+</button>
                    <button onClick={() => adicionarAoCarrinho(item)}>Adicionar ao Carrinho</button>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      <div id="carrinho">
        <h2>ℂ𝕒𝕣𝕣𝕚𝕟𝕙𝕠 :</h2>
        <div className="botoes-carrinho">
          <button onClick={limparCarrinho}>Limpar Carrinho</button>
          <button onClick={registrarPedido}>Registrar Pedido</button>
        </div>
        <ul>
          {carrinho.map((item, index) => (
            <li key={index}>
              <span className="item-nome">{item.nome}</span> - 
              <span className="quantidade"> Quantidade: {item.quantidade}</span> - 
              <span className="item-preco"> R${(item.preco * item.quantidade).toFixed(2)}</span>
            </li>
          ))}
        </ul>
      </div>

      <style jsx>{`
        .botoes-carrinho {
          display: flex;
          justify-content: flex-end;
          margin-bottom: 10px;
        }
      `}</style>
    </>
  );
}

const menuItens = [
  {
    titulo: '𝕃𝔸ℕℂℍ𝔼𝕊',
    itens: [
      { nome: 'X-salada', preco: 25.00 },
      { nome: 'X-bacon', preco: 28.00 },
      { nome: 'X-egg', preco: 24.00 },
      { nome: 'X-frango', preco: 22.00 },
      { nome: 'X-calabresa', preco: 26.00 },
      { nome: 'X-tudo', preco: 30.00 },
      { nome: 'X-vegetariano', preco: 23.00 },
    ],
  },
  {
    titulo: '𝕊𝕆𝔹ℝ𝔼𝕄𝔼𝕊𝔸𝕊',
    itens: [
      { nome: 'Chocolate', preco: 16.00 },
      { nome: 'Picolé', preco: 7.00 },
      { nome: 'Palha Italiana', preco: 13.00 },
      { nome: 'Açaí', preco: 18.00 },
      { nome: 'Pudim', preco: 14.00 },
    ],
  },
  {
    titulo: '𝔹𝔼𝔹𝕀𝔻𝔸𝕊',
    itens: [
      { nome: 'Suco de Laranja', preco: 8.00 },
      { nome: 'Suco de Goiaba', preco: 8.00 },
      { nome: 'Suco de Maçã', preco: 7.00 },
      { nome: 'Suco de Abacaxi', preco: 7.00 },
    ],
  },
];
